### ISSUE TITLE
Add a song editor

### ISSUE THREAD

**Issue by nh758** [jamesduncan/digihymnal#4]
The song editor, used for adding new songs, adding new translations, fixing/adding chords and notation. 

WYSIWYG - Drag and drop chords, adjust position relative to lyrics.

- [x] Can select a line
- [x] Can edit all elements of that line
- [x] Can navigate to other lines
- [x] Save button
- [x] Button triggers a save to local storage
- [x] Local storage sends to server...
- [x] Drag and drop chords
- [x] add translations

**Comment by Achoobert** [comment]
> How can we start editing (clean up i.e. extra info and spacing) and adding lyrics, chords and notation?

Will also need ability to 
move where a 'verse' starts
??Mark a line as metadata??
